# Generated by Django 5.0.6 on 2024-06-22 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_alter_customer_joined_customeruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 0, 14, 33, 424169)),
        ),
    ]
