# Generated by Django 5.0.6 on 2024-06-23 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0042_user_phone_number_alter_customer_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 23, 45, 2, 57072)),
        ),
    ]
