# Generated by Django 5.0.6 on 2024-07-08 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0045_customer_is_active_alter_customer_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 20, 14, 55, 76428)),
        ),
    ]
